import time
import numpy as np
from modlib.apps import Annotator
from modlib.devices import AiCamera
from modlib.models import COLOR_FORMAT, MODEL_TYPE, Model
from modlib.models.post_processors import pp_od_yolo_ultralytics

class YOLO(Model):
    def __init__(self):
        super().__init__(
            # Zip file generated by yolo export (imx format)
            model_file="/home/erwan/cap-robot/ai-camera/models/yolov8n-face-lindevs_imx_model/packerOut.zip", 
            model_type=MODEL_TYPE.CONVERTED,
            color_format=COLOR_FORMAT.RGB,
            preserve_aspect_ratio=False,
        )
        
        # Label loading
        try:
            self.labels = np.genfromtxt(
                "/home/erwan/cap-robot/ai-camera/models/yolov8n-face-lindevs_imx_model/labels.txt", 
                dtype=str, delimiter="\n"
            )
        except OSError:
            self.labels = ["Visage"]

    def post_process(self, output_tensors):
        return pp_od_yolo_ultralytics(output_tensors)


print("🤖 Initialisation de l'AI Camera (via modlib)...")
# 15 ou 16 FPS max pour éviter les Timeout du NPU
device = AiCamera(frame_rate=16) 
model = YOLO()
device.deploy(model)

print("🎯 IA déployée avec succès ! Recherche de visages...")

# Le flux s'ouvre proprement ici
with device as stream:
    for frame in stream:
        # On garde uniquement les détections avec confiance > 55%
        valid_detections = frame.detections[frame.detections.confidence > 0.55]
        
        if len(valid_detections) > 0:
            # La boucle magique de modlib : elle unpack proprement !
            # bbox contient [x_min, y_min, x_max, y_max]
            for bbox, score, class_id, _ in valid_detections:
                x_min, y_min, x_max, y_max = bbox
                
                # 🎯 CALCUL DU CENTRE POUR TES MOTEURS
                cx = (x_min + x_max) / 2
                cy = (y_min + y_max) / 2
                
                print(f"🎯 VISAGE CENTRÉ EN -> X: {cx:.3f} | Y: {cy:.3f} | Conf: {score*100:.1f}%")
                
                # On break pour ne traiter que le premier visage détecté à chaque frame
                # (Évite au robot de trembler s'il y a 2 personnes)
                break